### ISSUE TITLE
改进：能否在接收暂不支持的消息类型时显示消息来源

### ISSUE THREAD

**Issue by ckn4** [XYenon/efb-qq-plugin-go-cqhttp#2]
在接收语音等暂不支持的消息类型时，会显示“不支持的消息类型”，但会转发该提示信息到tg主端，这样会导致不知道该不支持的消息来自哪个联系人或者哪个群组。这种情况下，往往要打开QQ，查找这条消息是否来自重要的联系人或者是值得关注的消息，在添加群组较多的时候，会造成混乱。
希望在显示不支持的消息类型的提示时，能够显示更丰富的信息，例如：来自于”联系人:名称“或者来自于“群组:名称”

**Comment by Ashinch** [comment]
十分赞同！

某个群一直在发一些 “不支持的消息类型”，就会一直在 Bot 会话中提醒，并且也不知道该消息是来源于哪个会话，Bot 机器人一般都是开启声音用于及时接收其他未绑定会话的消息，却频繁收到 “不支持的消息类型” 的提醒，感觉有点打扰了，希望在收到 “不支持的消息类型” 时，如果是已 /link 的会话，能够直接归纳到该群组中显示，而不是在 Bot 机器人中提示。

这样对于希望接收该会话中 “不支持的消息类型” 提醒的人来说，可以得知消息来源，对于不想接收该会话中 “不支持的消息类型” 提醒的人来说，完全可以通过 TG 群组的通知静音来管控。

![](https://bucket-ashinch.oss-cn-hangzhou.aliyuncs.com/uPic/1625057020248.jpg)
